name: Deploy to GitHub Pages

on: 
  push:
    branches: [main]

# Agrega permisos explícitos
permissions:
  contents: write  # Permite escritura en el contenido del repositorio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: cp dist/index.html dist/404.html # Fallback para SPA
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist